# -*- coding: utf-8 -*-
"""SER_Model_Implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAly9kYNWl0c9iwrlygE6ORs6HUaW8Yy
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %autoreload 2
# %cd drive/MyDrive/Bradford/sem2/group_project/SER

import pandas as pd
import numpy as np
import os
import sys
import tensorflow as tf

import librosa
import librosa.display

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from keras.losses import mean_squared_error
# to play the audio files
from IPython.display import Audio

import keras
from keras.callbacks import ReduceLROnPlateau
from keras.models import Sequential
from keras.layers import Dense, Conv1D, MaxPooling1D, Flatten, Dropout, BatchNormalization
#from tensorflow.keras.utils import to_categorical

from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint


print("Running tensorflow version: {}".format(tf.keras.__version__))
print("Running tensorflow.keras version: {}".format(tf.__version__))
print("Running keras version: {}".format(keras.__version__))
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
tf.config.experimental.list_physical_devices('GPU')

gpus = tf.config.experimental.list_physical_devices('GPU')

import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Paths for data.
Ravdess = "D:/MastersDataset/Ravdess/"
Crema = "D:/MastersDataset/crema/AudioWAV/"
Tess = "D:/MastersDataset/tess/tess toronto emotional speech set data/TESS Toronto emotional speech set data/"
Savee = "D:/MastersDataset/surrey/ALL/"

print("Reading Ravdess")
ravdess_directory_list = os.listdir(Ravdess)

file_emotion = []
file_path = []
for dir in ravdess_directory_list:

    if dir == 'audio_speech_actors_01-24':
        print("skip diirectory -- : " + dir)
        continue
    # as their are 20 different actors in our previous directory we need to extract files for each actor.
    actor = os.listdir(Ravdess + dir)
    for file in actor:
        part = file.split('.')[0]
        part = part.split('-')
        # third part in each file represents the emotion associated to that file.
        file_emotion.append(int(part[2]))
        file_path.append(Ravdess + dir + '/' + file)

# dataframe for emotion of files
emotion_df = pd.DataFrame(file_emotion, columns=['Emotions'])

# dataframe for path of files.
path_df = pd.DataFrame(file_path, columns=['Path'])
Ravdess_df = pd.concat([emotion_df, path_df], axis=1)

# changing integers to actual emotions.
Ravdess_df.Emotions.replace(
    {1: 'neutral', 2: 'calm', 3: 'happy', 4: 'sad', 5: 'angry', 6: 'fear', 7: 'disgust', 8: 'surprise'}, inplace=True)
Ravdess_df.head()

Ravdess_df = Ravdess_df[Ravdess_df != 'surprise']
Ravdess_df = Ravdess_df[Ravdess_df != 'disgust']
Ravdess_df = Ravdess_df[Ravdess_df != 'calm']
Ravdess_df = Ravdess_df[Ravdess_df['Emotions'].notna()]


print("Reading Crema")

crema_directory_list = os.listdir(Crema)

file_emotion = []
file_path = []

for file in crema_directory_list:
    # storing file paths
    file_path.append(Crema + file)
    # storing file emotions
    part = file.split('_')
    if part[2] == 'SAD':
        file_emotion.append('sad')
    elif part[2] == 'ANG':
        file_emotion.append('angry')
    elif part[2] == 'DIS':
        file_emotion.append('disgust')
    elif part[2] == 'FEA':
        file_emotion.append('fear')
    elif part[2] == 'HAP':
        file_emotion.append('happy')
    elif part[2] == 'NEU':
        file_emotion.append('neutral')
    else:
        file_emotion.append('Unknown')

# dataframe for emotion of files
emotion_df = pd.DataFrame(file_emotion, columns=['Emotions'])

# dataframe for path of files.
path_df = pd.DataFrame(file_path, columns=['Path'])
Crema_df = pd.concat([emotion_df, path_df], axis=1)
Crema_df.head()

# Crema_df = Crema_df[Crema_df != 'fear']
Crema_df = Crema_df[Crema_df != 'disgust']
Crema_df = Crema_df[Crema_df != 'Unknown']
Crema_df = Crema_df[Crema_df['Emotions'].notna()]


print("Reading Tess")

tess_directory_list = os.listdir(Tess)

file_emotion = []
file_path = []

for dir in tess_directory_list:
    directories = os.listdir(Tess + dir)
    for file in directories:
        part = file.split('.')[0]
        part = part.split('_')[2]
        if part == 'ps':
            file_emotion.append('surprise')
        else:
            file_emotion.append(part)
        file_path.append(Tess + dir + '/' + file)

# dataframe for emotion of files
emotion_df = pd.DataFrame(file_emotion, columns=['Emotions'])

# dataframe for path of files.
path_df = pd.DataFrame(file_path, columns=['Path'])
Tess_df = pd.concat([emotion_df, path_df], axis=1)
Tess_df.head()
Tess_df = Tess_df[Tess_df != 'surprise']
Tess_df = Tess_df[Tess_df != 'disgust']
Tess_df = Tess_df[Tess_df['Emotions'].notna()]


print("Reading Savee")

savee_directory_list = os.listdir(Savee)

file_emotion = []
file_path = []

for file in savee_directory_list:
    file_path.append(Savee + file)
    part = file.split('_')[1]
    ele = part[:-6]
    if ele == 'a':
        file_emotion.append('angry')
    elif ele == 'd':
        file_emotion.append('disgust')
    elif ele == 'f':
        file_emotion.append('fear')
    elif ele == 'h':
        file_emotion.append('happy')
    elif ele == 'n':
        file_emotion.append('neutral')
    elif ele == 'sa':
        file_emotion.append('sad')
    else:
        file_emotion.append('surprise')

# dataframe for emotion of files
emotion_df = pd.DataFrame(file_emotion, columns=['Emotions'])

# dataframe for path of files.
path_df = pd.DataFrame(file_path, columns=['Path'])
Savee_df = pd.concat([emotion_df, path_df], axis=1)
Savee_df.head()
Savee_df = Savee_df[Savee_df != 'surprise']
Savee_df = Savee_df[Savee_df != 'disgust']
Savee_df = Savee_df[Savee_df['Emotions'].notna()]


# creating Dataframe using all the 4 dataframes we created so far.
data_path = pd.concat([Ravdess_df, Crema_df, Tess_df, Savee_df], axis=0)
data_path.to_csv("data_path.csv", index=False)
data_path.head()

plt.title('Count of Emotions', size=16)
sns.countplot(Ravdess_df.Emotions)
plt.ylabel('Count', size=12)
plt.xlabel('Emotions', size=12)
sns.despine(top=True, right=True, left=False, bottom=False)
plt.show()


# def create_waveplot(data, sr, e):
#     plt.figure(figsize=(10, 3))
#     plt.title('Waveplot for audio with {} emotion'.format(e), size=15)
#     librosa.display.waveplot(data, sr=sr)
#     plt.show()
#
#
# def create_spectrogram(data, sr, e):
#     # stft function converts the data into short term fourier transform
#     X = librosa.stft(data)
#     Xdb = librosa.amplitude_to_db(abs(X))
#     plt.figure(figsize=(12, 3))
#     plt.title('Spectrogram for audio with {} emotion'.format(e), size=15)
#     librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz')
#     # librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='log')
#     plt.colorbar()
#
#
emotion = 'angry'
path = np.array(Ravdess_df.Path[Ravdess_df.Emotions == emotion])[1]
data, sampling_rate = librosa.load(path)
# create_waveplot(data, sampling_rate, emotion)
# create_spectrogram(data, sampling_rate, emotion)
Audio(path)


def noise(data):
    noise_amp = 0.035 * np.random.uniform() * np.amax(data)
    data = data + noise_amp * np.random.normal(size=data.shape[0])
    return data


def stretch(data, rate=0.8):
    return librosa.effects.time_stretch(data, rate)


def shift(data):
    shift_range = int(np.random.uniform(low=-5, high=5) * 1000)
    return np.roll(data, shift_range)


def pitch(data, sampling_rate, pitch_factor=0.7):
    return librosa.effects.pitch_shift(data, sampling_rate, pitch_factor)


# taking any example and checking for techniques.
path = np.array(data_path.Path)[1]
data, sample_rate = librosa.load(path)
#
# plt.figure(figsize=(14, 4))
# librosa.display.waveplot(y=data, sr=sample_rate)
# Audio(path)
#
# x = noise(data)
# plt.figure(figsize=(14, 4))
# librosa.display.waveplot(y=x, sr=sample_rate)
# Audio(x, rate=sample_rate)
#
# x = stretch(data)
# plt.figure(figsize=(14, 4))
# librosa.display.waveplot(y=x, sr=sample_rate)
# Audio(x, rate=sample_rate)

"""## Data preparation"""


def extract_features(data):
    # ZCR
    result = np.array([])
    zcr = np.mean(librosa.feature.zero_crossing_rate(y=data).T, axis=0)
    result = np.hstack((result, zcr))  # stacking horizontally

    # Chroma_stft
    stft = np.abs(librosa.stft(data))
    chroma_stft = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T, axis=0)
    result = np.hstack((result, chroma_stft))  # stacking horizontally

    # MFCC
    mfcc = np.mean(librosa.feature.mfcc(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mfcc))  # stacking horizontally

    # Root Mean Square Value
    rms = np.mean(librosa.feature.rms(y=data).T, axis=0)
    result = np.hstack((result, rms))  # stacking horizontally

    # MelSpectogram
    mel = np.mean(librosa.feature.melspectrogram(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mel))  # stacking horizontally

    return result


def get_features(path):
    # duration and offset are used to take care of the no audio in start and the ending of each audio files as seen above.
    data, sample_rate = librosa.load(path, duration=2.5, offset=0.6)

    # without augmentation
    res1 = extract_features(data)
    result = np.array(res1)

    # data with noise
    noise_data = noise(data)
    res2 = extract_features(noise_data)
    result = np.vstack((result, res2))  # stacking vertically

    # data with stretching and pitching
    new_data = stretch(data)
    data_stretch_pitch = pitch(new_data, sample_rate)
    res3 = extract_features(data_stretch_pitch)
    result = np.vstack((result, res3))  # stacking vertically

    return result


X, Y = [], []
for path, emotion in zip(data_path.Path, data_path.Emotions):
    feature = get_features(path)
    for ele in feature:
        X.append(ele)
        # appending emotion 3 times as we have made 3 augmentation techniques on each audio file.
        Y.append(emotion)
    print(path)

Features = pd.DataFrame(X)
Features['labels'] = Y
Features.to_csv('features.csv', index=False)
Features.head()

import pickle

X = Features.iloc[:, :-1].values
Y = Features['labels'].values
# As this is a multiclass classification problem onehotencoding our Y.
encoder = OneHotEncoder()
Y = encoder.fit_transform(np.array(Y).reshape(-1, 1)).toarray()
# splitting data
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0, shuffle=True)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

import pickle

with open('encoder.pickle', 'wb') as f:
    pickle.dump(encoder, f)

# scaling our data with sklearn's Standard scaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

"""## Model Implementation"""

# model param config
k_size = 5
p_size = 5
drop_out_prob = 0.3
num_classes = 5
num_epochs = 50
batchsize = 64
# Reduce learning rate when a metric has stopped improving.
rlrp = ReduceLROnPlateau(monitor='loss', factor=0.4, verbose=1, patience=2, min_lr=0.0000001)

# model archeteture

model = Sequential()
model.add(
    Conv1D(256, kernel_size=k_size, strides=1, padding='same', activation='relu', input_shape=(x_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=p_size, strides=2, padding='same'))

model.add(Conv1D(256, kernel_size=k_size, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=p_size, strides=2, padding='same'))

model.add(Conv1D(128, kernel_size=k_size, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=p_size, strides=2, padding='same'))
model.add(Dropout(0.2))

model.add(Conv1D(64, kernel_size=k_size, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=p_size, strides=2, padding='same'))

model.add(Flatten())
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='adam', loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

"""## initial Model Training
short training for the purpose of veryfying the implementation.  full training with more epochs will be  done later
"""

history = model.fit(x_train, y_train, batch_size=batchsize, epochs=num_epochs, validation_data=(x_test, y_test),
                    callbacks=[rlrp])

print("Accuracy of our model on test data : ", model.evaluate(x_test, y_test)[1] * 100, "%")

epochs = [i for i in range(num_epochs)]
fig, ax = plt.subplots(1, 2)
train_acc = history.history['accuracy']
train_loss = history.history['loss']
test_acc = history.history['val_accuracy']
test_loss = history.history['val_loss']

fig.set_size_inches(20, 6)
ax[0].plot(epochs, train_loss, label='Training Loss')
ax[0].plot(epochs, test_loss, label='Testing Loss')
ax[0].set_title('Training & Testing Loss')
ax[0].legend()
ax[0].set_xlabel("Epochs")

ax[1].plot(epochs, train_acc, label='Training Accuracy')
ax[1].plot(epochs, test_acc, label='Testing Accuracy')
ax[1].set_title('Training & Testing Accuracy')
ax[1].legend()
ax[1].set_xlabel("Epochs")
plt.show()

"""## predicting on test data."""

pred_test = model.predict(x_test)
y_pred = encoder.inverse_transform(pred_test)

y_test = encoder.inverse_transform(y_test)
model.save("model2.h5")

df = pd.DataFrame(columns=['Predicted Labels', 'Actual Labels'])
df['Predicted Labels'] = y_pred.flatten()
df['Actual Labels'] = y_test.flatten()

df.head(10)

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(12, 10))
cm = pd.DataFrame(cm, index=[i for i in encoder.categories_], columns=[i for i in encoder.categories_])
sns.heatmap(cm, linecolor='white', cmap='Blues', linewidth=1, annot=True, fmt='')
plt.title('Confusion Matrix', size=20)
plt.xlabel('Predicted Labels', size=14)
plt.ylabel('Actual Labels', size=14)
plt.show()

print(classification_report(y_test, y_pred))

"""## Inference code 
following code can be used for integrating the SER into application backend
"""


def preprocess_data(test_file_path):
    x = []
    feature = get_features(test_file_path)
    for f in feature:
        x.append(f)
    features = pd.DataFrame(x)
    x = features.iloc[:, :].values

    # scaling our data with sklearn's Standard scaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    return x


def ser(audio_data, model_file):
    x_test = preprocess_data(audio_data)
    model = keras.models.load_model(model_file)
    pred = model.predict(x_test)

    with open('encoder.pickle', 'rb') as f:
        enc = pickle.load(f)
    emotion_detected = enc.inverse_transform(pred).flatten()
    # emotion_percentage=np.argmax(pred,axis=1) #todo
    return emotion_detected[0]  # , emotion_percentage


model_file = 'model2.h5'
file_name = 'D:/MastersDataset/Ravdess/Actor_03/03-01-05-01-01-02-03.wav'

# file_name='ravdess/Actor_01/03-01-01-01-01-01-01.wav'
pred = ser(file_name, model_file)

pred

